### ISSUE TITLE
Do you have discord?

### ISSUE THREAD

**Issue by SeekyCt** [chor64/PM-Model-Viewer#1]
(Sorry for making this an issue, didn't know of any other way to contact you)
It's cool to see someone else looking into SPM modding, would be interested in discussing stuff with you & I might be able to help you if you need any

**Comment by follycake** [comment]
I do, but i don't think it would be the best to like post my username publicly, would it?
I am pretty new to this stuff and do this as a hobby.

**Comment by follycake** [comment]
I just remembered that discord has a friend request system, and you do have your discord on your profile, so that's that.
Chor64#0302

**Comment by SeekyCt** [comment]
It's mostly just what you're comfortable with personally, I've had mine listed publicly in various places and never had any issues really (and any spam bots tend to target server invite links rather than usernames). I've sent a request now (assuming you meant #0302? I tried that and it seems to have worked), thanks :)
EDIT: I noticed now that github seems to have also removed the leading zero for me lol, guessing the same happened to you
